### ISSUE TITLE
Unable to change DefaultCourse to other difficulty 

### ISSUE THREAD

**Issue by edgarlim** [TJAPlayer3-Develop/TJAPlayer3-Develop#19]
**注意: お使いのTJAPlayer3-Developが最新のバージョンであること確認してください！**

## 内容
発生したバグ/問題の具体的な説明を書いてください。

Unable to change DefaultCourse to other difficulty.

## 発生手順
バグ/問題を発生させる方法が分かる場合、手順を記入してください。

1. Edit config.ini
2. Changed line DefaultCourse=3 to DefaultCourse=1
3. Config.ini saved
4. Execute program
5. Default course remains as Oni

## 正常時の挙動
バグ/問題がないと仮定した場合の、正しい挙動がどのようなものか記入してください。

The difficulty level should be Normal (1), not the default Oni (3)

## 動作環境
バグ/問題が発生した際に使用したコンピュータの環境を記入してください。

1. OS: Windows 10 Pro
2. CPU: Intel Core i5-4570T
3. RAM: 8GB
4. System Bit: 64-bit

## その他の情報
上記の内容のほかに提供できる情報がある場合、提供をお願いします。
例えば以下のようなものを提供していただけると助かります: (ある場合)
- 似ている/関連している他のバグ報告
- Config.iniファイル
- 使用しているスキンの各種Config.iniファイル
- クラッシュ時のエラー
- ログファイル
- バグ/問題の発生が確認できる.tjaファイル (音声は含めないでください)

![c8b1ebcc-5ad0-422c-beb0-4b63415a0d02](https://user-images.githubusercontent.com/6383084/96401834-0ac9cb00-1207-11eb-8d6f-f6b55fef185e.jpeg)

**Comment by Tomo-Tg** [comment]
It may be difficult to understand because it is in Japanese, but this bug has already been reported here.
https://github.com/TJAPlayer3-Develop/TJAPlayer3-Develop/issues/5

**Comment by edgarlim** [comment]
@Tomo-Tg Got it! Thank you for letting me know. :)
