### ISSUE TITLE
Quick Configが他の画像と被って見づらい

### ISSUE THREAD

**Issue by siromisop** [TJAPlayer3-Develop/TJAPlayer3-Develop#21]
**注意: お使いのTJAPlayer3-Developが最新のバージョンであること確認してください！**

## 内容
song selectの時、Quick Configが一番上に描写されてないので他の画像と被って見づらい

## 発生手順
バグ/問題を発生させる方法が分かる場合、手順を記入してください。

1. 起動
2. song select
3. F2押す

## 正常時の挙動
バグ/問題がないと仮定した場合の、正しい挙動がどのようなものか記入してください。

左の王冠の画像より上に描写

## 動作環境
バグ/問題が発生した際に使用したコンピュータの環境を記入してください。

CPU:AMD A10-6700
GPU:NVIDIA GeForce GTX 460
メモリ:16GB

## その他の情報
上記の内容のほかに提供できる情報がある場合、提供をお願いします。
例えば以下のようなものを提供していただけると助かります: (ある場合)
- 似ている/関連している他のバグ報告
- Config.iniファイル
- 使用しているスキンの各種Config.iniファイル
- クラッシュ時のエラー
- ログファイル
- バグ/問題の発生が確認できる.tjaファイル (音声は含めないでください)
![TJAPlayer3-Develop - v1 0 (WASAPI(0ms)) 2020_10_20 21_30_40](https://user-images.githubusercontent.com/55023767/96586871-8c5f4d00-131c-11eb-8c84-c9d3b394a8ab.png)

**Comment by brian218** [comment]
Fixed in commit dd3d611fca85ab1737ff220f221ed87c26e36422
