### ISSUE TITLE
曲ロード画面と演奏画面で文字が下にズレるバグ

### ISSUE THREAD

**Issue by Tomo-Tg** [TJAPlayer3-Develop/TJAPlayer3-Develop#37]
**注意: お使いのTJAPlayer3-Developが最新のバージョンであること確認してください！**

## 内容
曲ロード画面と演奏画面で文字が下にズレる

## 発生手順
バグ/問題を発生させる方法が分かる場合、手順を記入してください。
1. FOT-大江戸勘亭流 Std Eを使う
2. プレイ

## 正常時の挙動
下にズレない

## 動作環境
Windows１０
CPU　COREi7 7600U
メモリ 16GB
GPU IntelHDgraphics 620

## その他の情報
![TJAPlayer3-Develop - v1 0 (DirectSound) 2020-10-25 00-57-41_Moment](https://user-images.githubusercontent.com/66196203/97086402-044faf00-165e-11eb-9b7a-6e5a9ef87128.jpg)
![TJAPlayer3-Develop - v1 0 (DirectSound) 2020-10-25 -57-41_Moment](https://user-images.githubusercontent.com/66196203/97086406-07e33600-165e-11eb-9112-9f72e1977ca1.jpg)

**Comment by brian218** [comment]
![圖片](https://user-images.githubusercontent.com/17809637/98472505-79121400-222e-11eb-8a75-9a38e09b40d1.png)
Please check the latest release to see whether this problem got solved.
