### ISSUE TITLE
【対応求みます！】その他のジャンルに入っている曲をプレイしようとすると落ちるバグ

### ISSUE THREAD

**Issue by Tomo-Tg** [TJAPlayer3-Develop/TJAPlayer3-Develop#58]
**注意: お使いのTJAPlayer3-Developが最新のバージョンであること確認してください！**

## 内容
その他のジャンル（特集フォルダーなど）に入れた曲をプレイできない

## 発生手順
バグ/問題を発生させる方法が分かる場合、手順を記入してください。
1. その他のジャンル内の曲をプレイする
2. 落ちる

## 正常時の挙動
その他の曲をプレイできる

## 動作環境
Windows１０
CPU　COREi7 7600U
メモリ 16GB
GPU IntelHDgraphics 620

## その他の情報
<img width="597" alt="スクリーンショット 2020-11-07 014938" src="https://user-images.githubusercontent.com/66196203/98393070-230d6700-209c-11eb-9887-9dd8d8fc3f6c.png">

**Comment by brian218** [comment]
Fixed in commit 5570bb2fd7c4d05482b2e023c1c1a29202a0fee4
